Altinn/altinn-access-management

frontend/.github/workflows/yarn.build

Fix for running tests automatically when PR is created.
- #14

Create auto run tests workflow

---

.github/workflows/yarn.build

Add github workflow/pipeline
- #14

Create github workflow

---

.github/workflows/frontend.yarn.build

Trying to fix github workflow pipeline
- #14

Update and rename yarn.build to frontend.yarn.build

---

.github/workflows/build.yaml
.github/workflows/main.yml
frontend/.yarnrc.yml
frontend/package.json
frontend/yarn.lock

Set up github actions - Create build.yaml

---

backend/src/Altinn.Authorizationadmin/Altinn.AuthorizationAdmin.Tests/DelegationRequestTests.cs
backend/src/Altinn.Authorizationadmin/Altinn.AuthorizationAdmin.Tests/DelegationsControllerTest.cs
backend/src/Altinn.Authorizationadmin/Altinn.Authorizationadmin/Controllers/DelegationRequestsController.cs
backend/src/Altinn.Authorizationadmin/Altinn.Authorizationadmin/Controllers/DelegationsController.cs
backend/src/Altinn.Authorizationadmin/Altinn.Authorizationadmin/Controllers/HomeController.cs

Fixed basepath to match /accessmanagement/ also changed casing

Fixed basepath of API

---

backend/src/Altinn.Authorizationadmin/Altinn.AuthorizationAdmin.Tests/DelegationsControllerTest.cs
backend/src/Altinn.Authorizationadmin/Altinn.Authorizationadmin/Controllers/DelegationRequestsController.cs
backend/src/Altinn.Authorizationadmin/Altinn.Authorizationadmin/Controllers/DelegationsController.cs
backend/src/Altinn.Authorizationadmin/Altinn.Authorizationadmin/Controllers/HomeController.cs

Removed unused methods from openAPI

---

Dockerfile

Cleanup of dockerfile and changed port. Unsure if this help entrypoint issue

Fixed path and port

---

src/Altinn.AccessManagement/Configuration/ConsoleTraceService.cs

- updated for identical implementation of ConsoleTraceService across all repos owned by the authorization team
- upgraded altinn-authorization to Yuniql.PostgreSql version to 1.3.15

Syncronized implementations of ConsoleTraceService for postgresql version 1.3.15 upgrade

---

src/Altinn.AccessManagement.Core/Clients/Interfaces/IPartiesClient.cs
src/Altinn.AccessManagement.Core/Services/Interfaces/IRegister.cs
src/Altinn.AccessManagement.Core/Services/RegisterService.cs
src/Altinn.AccessManagement.Integration/Clients/PartiesClient.cs
src/Altinn.AccessManagement/Controllers/LookupController.cs
src/Altinn.AccessManagement/Mappers/AccessManagementMapper.cs
src/Altinn.AccessManagement/Mappers/DelegationMapper.cs
src/Altinn.AccessManagement/Models/PartyExternal.cs
src/Altinn.AccessManagement/Program.cs
src/Altinn.AccessManagement/Utilities/IdentificatorUtil.cs
test/Altinn.AccessManagement.Tests/Controllers/AuthenticationControllerTest.cs
test/Altinn.AccessManagement.Tests/Controllers/LookupControllerTest.cs
test/Altinn.AccessManagement.Tests/Mocks/PartiesClientMock.cs
test/Altinn.AccessManagement.Tests/Utils/AssertionUtil.cs
test/Altinn.AccessManagement.Tests/Utils/TestDataUtil.cs

Api endpoint and unit tests to lookup an organisation number
- #199

Api endpoint and unit tests to lookup an organisation number

---

.github/containerscan/allowedlist.yaml
src/Altinn.AccessManagement.Integration/Clients/ProfileClient.cs
src/Altinn.AccessManagement/appsettings.json

Update profile path

---

src/Altinn.AccessManagement/Controllers/BFF/DelegationsController.cs
test/Altinn.AccessManagement.Tests/Controllers/BFFDelegationsControllerTest.cs

modified the api route for bff

---

src/Altinn.AccessManagement/Controllers/BFF/DelegationsController.cs
test/Altinn.AccessManagement.Tests/Controllers/BFFDelegationsControllerTest.cs

Attempt with new api route

---

src/Altinn.AccessManagement/Configuration/CustomTelemetryInitializer.cs

Changed the rolename from the old "authorization-admin" to "accessmanagement"
- #93

-Changed rolename from "authorization-admin" to "accessmanagement"

---

src/Altinn.AccessManagement.Integration/Clients/PartiesClient.cs

Updated the register endpoints in parties client with platform register endpoint. Added platformaccesstoken for the endpoints

Updated register endpoints

---

.github/workflows/build-and-analyze-fork.yml
.github/workflows/build-and-analyze.yml
.github/workflows/codeql-analysis.yml
Dockerfile
src/Altinn.AccessManagement.Core/Altinn.AccessManagement.Core.csproj
src/Altinn.AccessManagement.Integration/Altinn.AccessManagement.Integration.csproj
src/Altinn.AccessManagement.Persistence/Altinn.AccessManagement.Persistence.csproj
src/Altinn.AccessManagement/Altinn.AccessManagement.csproj
test/Altinn.AccessManagement.Tests/Altinn.AccessManagement.Tests.csproj

Updated TargetFramework to net7.0

Updated TargetFramework to net7.0

---

src/Altinn.AccessManagement/Controllers/BFF/DelegationsController.cs
src/Altinn.AccessManagement/Controllers/DelegationsController.cs
test/Altinn.AccessManagement.Tests/Controllers/BFFDelegationsControllerTest.cs
test/Altinn.AccessManagement.Tests/Controllers/DelegationsControllerTest.cs

Return empty list when no delegations found

---

src/Altinn.AccessManagement.Core/Clients/Interfaces/IPartiesClient.cs
src/Altinn.AccessManagement.Core/Services/RegisterService.cs
src/Altinn.AccessManagement.Integration/Clients/PartiesClient.cs
test/Altinn.AccessManagement.Tests/Mocks/PartiesClientMock.cs

so that it matches the usage from Altinn.Register.
- #301

Changed input type of LookupPartyBySSNOrOrgNo to PartyLookup-object

---

src/Altinn.AccessManagement.Integration/Clients/PartiesClient.cs

Added _serialiserOptions to the Deserialize call

---

src/Altinn.AccessManagement/Filters/IdentityTelemetryFilter.cs

Changed url check to actualy check for accessmanagment not Authorization

---

src/Altinn.AccessManagement/Program.cs

-  Updated program.cs to set the hardcoded altinn well-known endpoint based on the new OidcProviders config
- #338

Fix broken AltinnStudioRuntime cookie authentication

---

src/Altinn.AccessManagement.Core/Models/AccessManagementResource.cs
src/Altinn.AccessManagement.Persistence/DelegationMetadataRepository.cs
src/Altinn.AccessManagement.Persistence/ResourceMetadataRepository.cs
test/Altinn.AccessManagement.Tests/Data/Json/InsertAccessManagementResource/InsertData_string.json
test/Altinn.AccessManagement.Tests/Data/Json/InsertAccessManagementResource/InsertData_string2.json
test/Altinn.AccessManagement.Tests/Data/Json/InsertAccessManagementResource/input1.json
test/Altinn.AccessManagement.Tests/Data/Json/InsertAccessManagementResource/input3.json
test/Altinn.AccessManagement.Tests/Data/Json/InsertAccessManagementResource/input4.json
test/Altinn.AccessManagement.Tests/Data/Json/InsertAccessManagementResource/input5.json

- Updated resourcetype to Resourcetype instead of string in AM resource model. 
- updated the repository classes to handle the same. 
- updated test data

Casing issue with ResourceType in AM Resource model

---

.github/pull_request_template.md

Test to see if this works to create a pull request template for access-management repo

suggestion for new repo pullrequest template

---

src/Altinn.AccessManagement/Altinn.AccessManagement.csproj

Bumps version of PEP package to new version which includes fix for bug with organization number and SSN header values

Bump PEP package from v1.2.0 to v1.2.1

---

src/Altinn.AccessManagement/Controllers/ErrorController.cs

Add ErrorController
To handle unhandled exception and ensure an ErrorModel in those scenarios
- #382

Add Error controller to AccessManagment

---

src/Altinn.AccessManagement.Core/Services/MaskinportenSchemaService.cs
src/Altinn.AccessManagement/Mappers/AccessManagementMapper.cs
test/Altinn.AccessManagement.Tests/Data/Json/MaskinportenSchema/admindelegations.json

Fix of incorrect mapping of covered by and offered by

Fixed incorrect mapping

---

src/Altinn.AccessManagement.Core/Altinn.AccessManagement.Core.csproj
src/Altinn.AccessManagement.Integration/Altinn.AccessManagement.Integration.csproj
src/Altinn.AccessManagement.Persistence/Altinn.AccessManagement.Persistence.csproj
src/Altinn.AccessManagement/Altinn.AccessManagement.csproj
test/Altinn.AccessManagement.Tests/Altinn.AccessManagement.Tests.csproj

Some patching

---

test/K6/src/tests/maskinporten/maskinporten.js

Added cleanup step to two maskinportenschema tests.
- #417

Added cleanup step to two maskinportenschema tests

---

src/Altinn.AccessManagement/Altinn.AccessManagement.csproj
src/Altinn.AccessManagement/Program.cs
test/Altinn.AccessManagement.Tests/Controllers/DelegationsControllerTest.cs
test/Altinn.AccessManagement.Tests/Controllers/LookupControllerTest.cs
test/Altinn.AccessManagement.Tests/Controllers/MaskinportenSchemaControllerTest.cs
test/Altinn.AccessManagement.Tests/Controllers/ResourceControllerTest.cs
test/Altinn.AccessManagement.Tests/Controllers/RightsControllerTest.cs
test/Altinn.AccessManagement.Tests/Mocks/SigningKeyResolverMock.cs

Updated access token. Fixed breaking changes

Updated access token. Fixed breaking changes

---

src/Altinn.AccessManagement.Core/Enums/ResourceRegistry/ResourcePartyType.cs
src/Altinn.AccessManagement.Core/Enums/ResourceRegistry/ResourceType.cs
src/Altinn.AccessManagement.Core/Models/ResourceRegistry/ContactPoint.cs
src/Altinn.AccessManagement.Core/Models/ResourceRegistry/ServiceResource.cs
src/Altinn.AccessManagement.Core/Services/MaskinportenSchemaService.cs
src/Altinn.AccessManagement.Core/Services/PolicyInformationPoint.cs
src/Altinn.AccessManagement/Enums/ResourceRegistry/ResourcePartyTypeExternal.cs
src/Altinn.AccessManagement/Enums/ResourceRegistry/ResourceTypeExternal.cs
src/Altinn.AccessManagement/Mappers/AccessManagementMapper.cs
src/Altinn.AccessManagement/Models/ContactPointExternal.cs
src/Altinn.AccessManagement/Models/ServiceResourceExternal.cs
test/Altinn.AccessManagement.Tests/Data/Json/MaskinportenSchema/MaskinportenScopeDelegation/mp_validation_problem_details/from_p1/to_p2/ExpectedOutput_InvalidResourceRegistryId.json
test/Altinn.AccessManagement.Tests/Data/Json/MaskinportenSchema/MaskinportenScopeDelegation/mp_validation_problem_details/from_p1/to_p2/ExpectedOutput_InvalidResourceType.json
test/Altinn.AccessManagement.Tests/Utils/AssertionUtil.cs
test/Altinn.AccessManagement.Tests/Utils/TestDataUtil.cs

This PR udates the models corresponding to the ServiceResource models in the Resource Registry.
Some minor code changes have been made to Core code, to mirror the changes in these models and any tests broken by these changes have been fixed.
This PR is meant to work in tandem with the [similar changes to the BFF.](https://github.com/Altinn/altinn-access-management-frontend/issues/546)
- #500

Update ServiceResource models

---

src/Altinn.AccessManagement.Core/Enums/ResourceRegistry/ResourcePartyType.cs
src/Altinn.AccessManagement/Enums/ResourceRegistry/ResourcePartyTypeExternal.cs

Hotfix: Added enum serialization to resourcePartyType

Added enum serialization to resourcePartyType

---

.github/workflows/run-bruno-tests.yml
test/Bruno/Altinn.AccessManagement/collection.bru

test: setup automatic running of bruno on CI

---

test/K6/src/tests/access-management/maskinporten/maskinporten.js

Fixed maskinportenschema K6 tests

Fixed maskinportenschema K6 tests

---

.gitignore
test/Bruno/Altinn.AccessManagement/Automatic Test Collection/Maskinportenschema/getMaskinPortenSchemaOfferedTest.bru
test/Bruno/Altinn.AccessManagement/Automatic Test Collection/Maskinportenschema/getMaskinPortenSchemaReceivedTest.bru
test/Bruno/Altinn.AccessManagement/Automatic Test Collection/Maskinportenschema/postMaskinportenDAGLCannotDelegateNUFResource.bru
test/Bruno/Altinn.AccessManagement/Automatic Test Collection/Maskinportenschema/postMaskinportenSchemaToOrgNumberTest.bru
test/Bruno/Altinn.AccessManagement/Automatic Test Collection/Maskinportenschema/postMaskinportenSchemaToPartyIdTest.bru

updated bruno test names so test results in pipeline make sense.
- #549

updated bruno test names

---

src/Altinn.AccessManagement.Persistence/DelegationMetadataRepository.cs

#611 introduced a change in the db connection setup in DelegationMetadataRepository which performs an explisit open db connection pr. db funtion call.
- #615

Too many db connections being opened

---

src/Altinn.AccessManagement/Enums/DetailCodeExternal.cs

Added all values from internal to external

---

src/Altinn.AccessManagement.Persistence/Altinn.AccessManagement.Persistence.csproj
src/Altinn.AccessManagement.Persistence/Configuration/TelemetryConfig.cs
src/Altinn.AccessManagement.Persistence/DelegationMetadataRepository.cs
src/Altinn.AccessManagement.Persistence/Extensions/ActivityExtensions.cs
src/Altinn.AccessManagement.Persistence/PolicyRepository.cs
src/Altinn.AccessManagement.Persistence/ResourceMetadataRepository.cs
src/Altinn.AccessManagement/Altinn.AccessManagement.csproj
src/Altinn.AccessManagement/Program.cs
src/Altinn.AccessManagement/appsettings.json

Implementing OpenTelemetry for Altinn.AccessManagement.Persistence to get better information from the data access layer. This is triggered from the cleanup postgres queries issue.
- #558

OpenTelemetry for Altinn.AccessManagement.Persistence

---

test/Bruno/Altinn.AccessManagement/Manual Test Collection/RightsInternal/CreateDelegation/Authorized Parties Test Data Setup/Altinn 2 Service/Person to Person.bru
test/Bruno/Altinn.AccessManagement/Manual Test Collection/RightsInternal/CreateDelegation/Authorized Parties Test Data Setup/Altinn App/Person to Person.bru
test/Bruno/Altinn.AccessManagement/Manual Test Collection/RightsInternal/CreateDelegation/Authorized Parties Test Data Setup/Altinn App/Sub to Person.bru
test/Bruno/Altinn.AccessManagement/Manual Test Collection/RightsInternal/CreateDelegation/Authorized Parties Test Data Setup/Generic Access Resource/Mainunit to Person.bru
test/Bruno/Altinn.AccessManagement/Manual Test Collection/RightsInternal/CreateDelegation/Authorized Parties Test Data Setup/Generic Access Resource/Person to Person.bru
test/Bruno/Altinn.AccessManagement/Manual Test Collection/RightsInternal/CreateDelegation/Authorized Parties Test Data Setup/Generic Access Resource/Subunit to Person.bru

- Added Altinn 2 service request example
- Updated all 'to Person' requests to use the new attribute type urn:altinn:person:identifier-no

Bruno fix manual rights delegation requests

---

src/Altinn.AccessManagement.Core/Helpers/RightsHelper.cs
src/Altinn.AccessManagement.Core/Services/SingleRightsService.cs
test/Altinn.AccessManagement.Tests/Controllers/RightsInternalControllerTest.cs
test/Altinn.AccessManagement.Tests/Data/Json/DelegationCheck/ttd_apps-test/from_p50005545/authn_u20000490.json
test/Altinn.AccessManagement.Tests/Data/Json/DelegationCheck/ttd_apps-test/from_p50005546/authn_u20000490.json
test/Altinn.AccessManagement.Tests/Data/Json/DelegationCheck/ttd_apps-test/request.json
test/Altinn.AccessManagement.Tests/Data/Parties/parties.json
test/Altinn.AccessManagement.Tests/Data/Resources/resourceList.json
test/Altinn.AccessManagement.Tests/Data/Xacml/3.0/AltinnApps/ttd/apps-test/policy.xml

-Added test and testdata to test this
-Refactored the Analyze Helper method: Removed unused code and changed to fetch rolelist only once.
- #690

- Changed Code to filter away Role details for ServiceOwner rules

---

src/Altinn.AccessManagement.Core/Altinn.AccessManagement.Core.csproj
src/Altinn.AccessManagement.Core/Services/PolicyInformationPoint.cs
src/Altinn.AccessManagement/Altinn.AccessManagement.csproj

Skal ikke inkludere tilganger gitt fra personens nøkkelrolleenheter
- TFS-64268

Fiks for henting av delegerte tilganger fra person

---

test/Altinn.AccessManagement.Tests/Fixtures/PostgresFixture.cs

* add creation of user if not exists in PostgresFixture
* add error message in exception
- #738

Failed to Create User 

---

src/Altinn.AccessManagement.Core/Repositories/Interfaces/IDelegationMetadataRepository.cs
src/Altinn.AccessManagement.Core/Repositories/Interfaces/IResourceMetadataRepository.cs
src/Altinn.AccessManagement.Persistence/Altinn.AccessManagement.Persistence.csproj
src/Altinn.AccessManagement.Persistence/Configuration/TelemetryConfig.cs
src/Altinn.AccessManagement.Persistence/DelegationMetadataRepo.cs
src/Altinn.AccessManagement.Persistence/DelegationMetadataRepository.cs
src/Altinn.AccessManagement.Persistence/Extensions/ActivityExtensions.cs
src/Altinn.AccessManagement.Persistence/PolicyRepository.cs
src/Altinn.AccessManagement.Persistence/ResourceMetadataRepo.cs
src/Altinn.AccessManagement.Persistence/ResourceMetadataRepository.cs
src/Altinn.AccessManagement/Program.cs
src/Altinn.AccessManagement/appsettings.Development.json
test/Altinn.AccessManagement.Tests/Mocks/DelegationMetadataRepositoryMock.cs
test/Altinn.AccessManagement.Tests/Mocks/ResourceMetadataRepositoryMock.cs

Moved queries from procedures to code.
- #558

#558 - New Repo for Sql Queries

---

src/Altinn.AccessManagement.Persistence/DelegationMetadataRepo.cs
src/Altinn.AccessManagement.Persistence/ResourceMetadataRepo.cs

Bugfix for Connectionstrings in new Repo
- #721 
- #558

Connectionstring fix for new repos

---

src/Altinn.AccessManagement.Persistence/DelegationMetadataRepo.cs
src/Altinn.AccessManagement.Persistence/Extensions/PersistenceDependencyInjectionExtensions.cs
src/Altinn.AccessManagement/Program.cs

Multiple bugfixes for new sql implementation
- #558

558 - bugfix sql

---

src/Altinn.AccessManagement.Persistence/DelegationMetadataRepo.cs

- Fixed bug with a missing space in the query.
- Fixed bug where DbNull.Value failed casting.
- #558

#558 - Sql querystring bug

---

src/Altinn.AccessManagement.Persistence/DelegationMetadataRepo.cs

Fixed parameter typo in sql repo
- #558

#558 - Fixed parameter typo in sql repo

---

src/Altinn.AccessManagement.Persistence/DelegationMetadataRepo.cs

SqlBugfix - DelegationChangeType mapping
- #558

SqlBugfix - DelegationChangeType mapping

---

src/Altinn.AccessManagement.Persistence/DelegationMetadataRepo.cs

There was syntax errors in the query sendt to Postgree for executuion ending in api to fail.
Fix missing commas in query causing the querty to throw an exeption when performed
- #772 #558

Fixing error in Query

---

src/Altinn.AccessManagement.Persistence/DelegationMetadataRepo.cs

The join was performed on resourceid not on changeid as it should
- #772 
- #558

Changed the join directive to join on correct value

---

src/Altinn.AccessManagement.Core/Services/Altinn2RightsService.cs
test/Altinn.AccessManagement.Tests/Controllers/V2RightsInternalControllerTest.cs
test/Altinn.AccessManagement.Tests/Fixtures/PostgresFixture.cs
test/Altinn.AccessManagement.Tests/Scenarios/DelegationScenarios.cs
test/Altinn.AccessManagement.Tests/Seeds/ResourceSeeds.cs

extend get offered with logic to handle possible deleted apps
- #769

harden get offered delegations to support deleted applications

---

Directory.Build.props
Directory.Build.targets
Directory.Packages.props
Dockerfile
src/Altinn.AccessManagement.Core/Altinn.AccessManagement.Core.csproj
src/Altinn.AccessManagement.Integration/Altinn.AccessManagement.Integration.csproj
src/Altinn.AccessManagement.Persistence/Altinn.AccessManagement.Persistence.csproj
src/Altinn.AccessManagement/Altinn.AccessManagement.csproj
src/Directory.Build.props
test/Altinn.AccessManagement.Tests/Altinn.AccessManagement.Tests.csproj
test/Altinn.AccessManagement.Tests/Seeds/EnterpriseUserSeeds.cs
test/Altinn.AccessManagement.Tests/Seeds/Interfaces.cs
test/Altinn.AccessManagement.Tests/Seeds/MaskinPortenSchemaResourceSeeds.cs
test/Altinn.AccessManagement.Tests/Seeds/OrganizationSeeds.cs
test/Altinn.AccessManagement.Tests/Seeds/PersonSeeds.cs
test/Altinn.AccessManagement.Tests/Seeds/ResourceSeeds.cs
test/Directory.Build.props

* add centralized package versioning
* trim csproj files
* add directory build props for source code
* add test dependencies for test project. Remember to use prop <IsTestProject>true</IsTestProject>
- #778

Tidy project dependencies

---

src/Altinn.AccessManagement/AccessManagementHost.cs

Add key vault configuration for reading certs 
- #789

Add key vault configuration

---

src/Altinn.AccessManagement.Core/Enums/ResourceRegistry/ResourceType.cs

Added resource type for correspondence and broker

---

src/Altinn.AccessManagement.Persistence/DelegationMetadataRepo.cs

Make user delegated Altinn apps great again

---

Directory.Packages.props
src/Altinn.AccessManagement/appsettings.Development.json
src/Altinn.AccessManagement/appsettings.json

UseNewQueryRepo feature toggle default ON

---

src/Altinn.AccessManagement.Core/Models/DelegationChange.cs
src/Altinn.AccessManagement/Models/DelegationChangeExternal.cs

Bugfix | Make DelegationChange.InstanceId nullable

---

test/Bruno/Altinn.AccessManagement/Automatic Test Collection/RightsInternal/tilg can delegate altinn app they have access to.bru
test/Bruno/Altinn.AccessManagement/Automatic Test Collection/RightsInternal/tilg successfully delegated app and resource.bru
test/Bruno/Altinn.AccessManagement/Testdata/rights-delegations/at22testdata.json
test/Bruno/Altinn.AccessManagement/Testdata/rights-delegations/tt02testdata.json

Updated the testdata file for TT02 bruno tests.
- #{insert issue number here}

added tt02 testdata for bruno tests

---

src/Altinn.AccessManagement/AccessManagementHost.cs
src/Altinn.AccessManagement/Controllers/ResourceOwnerAPI/AppsInstanceDelegationController.cs
test/Altinn.AccessManagement.Tests/Controllers/ResourceOwnerAPI/AppsInstanceDelegationControllerTest.cs

issues/862:  add scopes for token handlers and remove double DPI init for access token
