src/Altinn.AccessManagement/Program.cs

Migration script folder has been moved from AccessManagement to Persistance project folder.
Docker file copy correctly from it's new location but changes in Program.cs for reading the scripts at runtime will differ when running locally on dev vs aks pods, where Dev need to navigate through parent folder.
- #184

Fix workspace path diff for Migration scripts between pods and dev

---

src/Altinn.AccessManagement/Views/Home/Index.cshtml

Currently when the react app is run from backend the backgorund color isn't set. This PR sets the background color to the default background color.

Update react app's backgorund-color

---

test/Altinn.AccessManagement.Tests/Data/ResourceRegistryResources/digdirs_company_car/resource.json
test/Altinn.AccessManagement.Tests/Data/ResourceRegistryResources/jks_audi_etron_gt/resource.json

- Increased mock data ValidTo date to 2099 to fix broken integration tests

Fix for Resource Registry service mock data having 2022 ValidTo date

---

src/Altinn.AccessManagement.Persistence/Migration/v0.07-accessmanagement/02-setup-tables.sql
src/Altinn.AccessManagement.Persistence/Migration/v0.09-accessmanagement/02-setup-tables.sql
src/Altinn.AccessManagement/appsettings.json

Turn DB connection back on and fix db deploy for removal of resourcestatus column
- EnableDBConnection again
- remove resourceStatus column also from index in existing v07 script (meaning for clean deploy will not be created and then dropped again, eg. in TT02 and Prod)
- Since drop of column in v09 script will auto drop the index on the table it will need to recreate the index with just the type column
- #233

Turn DB connection back on and fix db deploy for removal of resourcestatus column

---

test/K6/src/Helpers/TestdataHelper.js

Some K6 tests can only be run on a certain sbl build version or higher, and the function that does the comparison will sometimes give return false when it should return true.
As an example, the current build is 23.1, and the function checks if it is higher than 22.5. It compares the major and minor versions separately, so even if the major version is higher (23 > 22), it returns false because the minor version is lower (1 < 5). Added a fix where if the major version is higher it returns true, while if it is equal, then it will check the minor version.
- #265

Fix sbl buildversion check that incorrectly skips a K6 test

---

src/Altinn.AccessManagement.Integration/Clients/PartiesClient.cs

Fetching partylist from localtest requires enumconverter for json.

Fix for fetching partylist from localtest

---

test/K6/src/tests/delegations/inheritancev2.js

K6 tests cannot log in with enterprise users because the pipeline does not have access to the sblbridge endpoint. Instead of logging in to get the right userid and partyid, the tests will instead get them from the pipeline variables.
- #279

remove login with sblbridge in K6 tests

---

test/K6/src/tests/delegations/inheritancev2.js

The test `delegationToOrgIsInheritedByECUserViaKeyrole` does not completely remove all rules in the cleanup step. Updated it so it correctly deletes all rules used in the test.
- #284

Fixed cleanup step in a k6 test

---

src/Altinn.AccessManagement.Core/Repositories/Interfaces/IDelegationMetadataRepository.cs
src/Altinn.AccessManagement.Core/Services/PolicyAdministrationPoint.cs
src/Altinn.AccessManagement.Persistence/DelegationMetadataRepository.cs
src/Altinn.AccessManagement/Controllers/DelegationsController.cs
test/Altinn.AccessManagement.Tests/Mocks/DelegationMetadataRepositoryMock.cs
test/Altinn.AccessManagement.Tests/PolicyAdministrationPointTest.cs

- Removed resource lookup from WriteDelegationPolicyInternal and DeleteAllRulesInPolicy
- In both cases its only used for setting ResourceType on the DelegationChange and used for switching whether it's a App delegation change or ResourceRegistry delegation change that is to be written to the PostgreSQL database.
- Changed this switching to instead just use the ResourceAttributeMatchType
- #147

Removed unnecessary lookup call to resource registry from internal WritePolicy operations

---

src/Altinn.AccessManagement.Integration/Clients/PartiesClient.cs
src/Altinn.AccessManagement/Controllers/LookupController.cs

Added the use of JsonSerializerOptions to the method LookupPartyBySSNOrOrgNo and made the serializerOptions variable globally available in PartiesClient.cs.
Also changed the response if orgnr in input returns no results.

Added the use of JsonSerializerOptions to LookupPartyBySSNOrOrgNo

---

src/Altinn.AccessManagement.Integration/Clients/ResourceRegistryClient.cs

Removed doubled API path from ResourceRegistryClient
After cleanup of configuration values in issue #311 there is now a double API path in config value and in client implementation.
- Removed the api path from the client
- #322

Removed doubled API path from ResourceRegistryClient

---

src/Altinn.AccessManagement.Core/Constants/AuthzConstants.cs
src/Altinn.AccessManagement.Core/Services/DelegationsService.cs
src/Altinn.AccessManagement.Integration/Clients/ResourceRegistryClient.cs
src/Altinn.AccessManagement/Controllers/DelegationsController.cs
src/Altinn.AccessManagement/Controllers/ResourceController.cs
src/Altinn.AccessManagement/Program.cs
src/Altinn.AccessManagement/Utilities/MaskinportenSchemaAuthorizer.cs
src/Altinn.AccessManagement/appsettings.json
test/Altinn.AccessManagement.Tests/Controllers/DelegationsControllerTest.cs
test/Altinn.AccessManagement.Tests/Utils/PrincipalUtil.cs

- Setup scope authorization policy requiring either scope "altinn:maskinporten/delegations" or "altinn:maskinporten/delegations.admin" for access to operation
- Implemented custom authorization on the lookup scope, for whether authenticated org has the admin scope or owns the scope prefix (defined in consumer_prefix claim from maskinporten token)
- Switched config for well-known endpoints in order to support both ver2 and test environments/issuers from maskinporten (Separate PR made for environment deploy variables will be merged as well)
- Fixes for some minor null-reference errors found during manual integration testing with SBL proxy API
- #299

Adding scope authorization for Maskinporten delegations API

---

src/Altinn.AccessManagement.Persistence/DelegationMetadataRepository.cs

Remove casing conversion as resourcetype is saved as "MaskinportenSchema" in both resourceregistry and accessmanagement

Remove casing conversion for resourcetype

---

src/Altinn.AccessManagement.Core/Services/DelegationsService.cs
test/Altinn.AccessManagement.Tests/Mocks/PartiesClientMock.cs

Register endpoint for lookup of Party based on PartyId requires user authorization for the reportee (have the party in their reporteelist).
Backend lookups should not be limited by user authorization. In this case looking up the party which is to receive a delegation.
- #334

Fix backend PartyId lookup to use endpoint without user authorization

---

src/Altinn.AccessManagement.Core/Services/DelegationsService.cs

Both the functions was missing check whether delegationChanges from DB is empty, causing empty PartyId list lookups and 404 not found results from Register
- #347

Fix so GetReceivedDelegations/GetOfferedDelegations return empty result earlier

---

test/K6/src/tests/delegations/inheritancev2.js

pipeline logs does not like console.log(), and counts them as warnings. Removed "showTestData()" that prints a lot of debug info
- #302

Removed "showTestData()" that prints a lot of debug info

---

src/Altinn.AccessManagement.Core/Models/Delegation.cs
src/Altinn.AccessManagement.Core/Services/ContextRetrievalService.cs
src/Altinn.AccessManagement.Core/Services/DelegationsService.cs
src/Altinn.AccessManagement.Integration/Clients/PartiesClient.cs
test/Altinn.AccessManagement.Tests/Controllers/LookupControllerTest.cs
test/Altinn.AccessManagement.Tests/Data/Parties/parties.json
test/Altinn.AccessManagement.Tests/Mocks/MessageHandlerMock.cs
test/Altinn.AccessManagement.Tests/Mocks/PartiesClientMock.cs

ContextRetrievalService.GetPartyForUser had a bug where it would return result after the first reportee with child reportees, whether or not the reportee was found among the child reportees.
Fixed some minor compile warnings and error logging in PartiesClient
- #371

Fix for bug in lookup/reportee/{partyId}

---

test/K6/src/tests/maskinporten/maskinporten.js

Updated maskinportenskema tests to only run if environment is AT23, as the other environments aren't ready yet.
- #368

Updated maskinportenskema tests to only run if environment is AT23

---

test/K6/src/api/platform/authorization/maskinporten.js
test/K6/src/buildrequestheaders.js
test/K6/src/tests/maskinporten/maskinporten.js

Added a test that delegates maskinportenschema using offeredby's orgnumber in header.
- #277

Added K6 test for maskinportenschema with offeredby's org number in header

---

src/Altinn.AccessManagement.Core/Services/ContextRetrievalService.cs

Fixes a bug in the implementation of ContextRetrievalService.GetPartiesAsync which still makes an empty partyId list lookup to register when all party information is found in cache.
- #425

Fix for empty GetPartyList lookups when found in cache

---

src/Altinn.AccessManagement/Controllers/ResourceController.cs
test/Altinn.AccessManagement.Tests/Controllers/ResourceControllerTest.cs

Implementation has already been moved to BFF and can be removed from the access management backend API
- #309

Remove unused maskinporten schema resource API

---

src/Altinn.AccessManagement.Core/Services/Interfaces/IResourceAdministrationPoint.cs
src/Altinn.AccessManagement.Core/Services/ResourceAdministrationPoint.cs

Added both ResourceType filter and null check on ResourceReferences when getting Resources based on matching Scope reference.
- #513

Hotfix for missing MaskinportenSchema filter and ResourceReference null check

---

src/Altinn.AccessManagement.Persistence/DelegationMetadataRepository.cs
src/Altinn.AccessManagement.Persistence/Extensions/ActivityExtensions.cs
src/Altinn.AccessManagement.Persistence/ResourceMetadataRepository.cs

Hotfix for bug with AddSqlTags in Persistence
System.NullReferenceException: Object reference not set to an instance of an object.
at Altinn.AccessManagement.Persistence.Extensions.ActivityExtensions.AddSqlTags(Activity activity, NpgsqlCommand command) in /app/src/Altinn.AccessManagement.Persistence/Extensions/ActivityExtensions.cs:line 22
- #{insert issue number here}

Hotfix for bug with AddSqlTags in Persistence

---

src/Altinn.AccessManagement.Core/Asserters/AttributeMatchAsserter.cs
src/Altinn.AccessManagement.Core/Helpers/DelegationHelper.cs
src/Altinn.AccessManagement.Core/Resolvers/Altinn/AltinnResolver.cs
src/Altinn.AccessManagement.Core/Resolvers/Altinn/PartyAttributeResolver.cs
src/Altinn.AccessManagement.Core/Resolvers/Altinn/UserAttributeResolver.cs
src/Altinn.AccessManagement.Core/Resolvers/Extensions/ResolverExtensions.cs
src/Altinn.AccessManagement.Core/Resolvers/Urn.cs
src/Altinn.AccessManagement.Core/Services/SingleRightsService.cs
src/Altinn.AccessManagement/Controllers/RightsInternalController.cs
test/Altinn.AccessManagement.Tests/Controllers/RightsInternalControllerTest.cs
test/Altinn.AccessManagement.Tests/Data/TestDataRevokeOfferedDelegationExternal.cs
test/Altinn.AccessManagement.Tests/Data/TestDataRevokeReceivedDelegationExternal.cs
test/Bruno/Altinn.AccessManagement/Manual Test Collection/RightsInternal/CreateDelegation/Revoke Test Data Setup/Asle to Hovdebygda.bru
test/Bruno/Altinn.AccessManagement/Manual Test Collection/RightsInternal/CreateDelegation/Revoke Test Data Setup/Kasper to Asle.bru
test/Bruno/Altinn.AccessManagement/Manual Test Collection/RightsInternal/CreateDelegation/Revoke Test Data Setup/Ørsta to Asle.bru
test/Bruno/Altinn.AccessManagement/Manual Test Collection/RightsInternal/CreateDelegation/Revoke Test Data Setup/Ørsta to Hovdebygda.bru
test/Bruno/Altinn.AccessManagement/Manual Test Collection/RightsInternal/RevokeOffered/Asle to Hovdebygda.bru
test/Bruno/Altinn.AccessManagement/Manual Test Collection/RightsInternal/RevokeOffered/Kasper to Asle.bru
test/Bruno/Altinn.AccessManagement/Manual Test Collection/RightsInternal/RevokeOffered/Ørsta to Asle.bru
test/Bruno/Altinn.AccessManagement/Manual Test Collection/RightsInternal/RevokeOffered/Ørsta to Hovdebygda.bru
test/Bruno/Altinn.AccessManagement/Manual Test Collection/RightsInternal/RevokeReceived/Asle From Kasper.bru
test/Bruno/Altinn.AccessManagement/Manual Test Collection/RightsInternal/RevokeReceived/Asle From Ørsta.bru
test/Bruno/Altinn.AccessManagement/Manual Test Collection/RightsInternal/RevokeReceived/Hovdebygda From Asle.bru
test/Bruno/Altinn.AccessManagement/Manual Test Collection/RightsInternal/RevokeReceived/Hovdebygda From Ørsta.bru

Cleanup of valid input attributes and resolver logic to only support the internal attribute ids used by the current Altinn 2 integration: urn:altinn:userid and urn:altinn:partyid
Added manual Bruno test requests for all scenarios for both received and offered for both userid and party id
- #613

Fix Revoke support for both UserId and PartyId as From and To attributes

---

src/Altinn.AccessManagement.Core/Clients/Interfaces/IAltinn2RightsClient.cs
src/Altinn.AccessManagement.Core/Services/Altinn2RightsService.cs
src/Altinn.AccessManagement.Core/Services/Interfaces/IAltinn2RightsService.cs
src/Altinn.AccessManagement.Integration/Clients/Altinn2RightsClient.cs
src/Altinn.AccessManagement/Controllers/RightsInternalController.cs
test/Altinn.AccessManagement.Tests/Controllers/Altinn2RightsControllerTest.cs
test/Altinn.AccessManagement.Tests/Mocks/Altinn2RightsClientMock.cs
test/Bruno/Altinn.AccessManagement/Manual Test Collection/RightsInternal/ClearAccessCache/Ørsta to Asle.bru
test/Bruno/Altinn.AccessManagement/Manual Test Collection/RightsInternal/ClearAccessCache/Ørsta to Hovdebygda.bru
test/Bruno/Altinn.AccessManagement/Manual Test Collection/RightsInternal/ClearAccessCache/Ørsta to OrstaECUser.bru

- Added new endpoint along-side existing internal rights operations
- Added implementation in Altinn2RightService and Altinn2RightsClient
- Added Bruno manual test requests
- #648

Internal API endpoint for clearing access cache

---

src/Altinn.AccessManagement.Core/Models/AuthorizedParty/AuthorizedParty.cs
test/Altinn.AccessManagement.Tests/Data/Json/AuthorizedParties/AccessManagerGettingOrgList/BothAltinn3AndAltinn2.json
test/Altinn.AccessManagement.Tests/Data/Json/AuthorizedParties/MainUnitAndSubUnitToOrg/BothAltinn3AndAltinn2.json
test/Altinn.AccessManagement.Tests/Data/Json/AuthorizedParties/MainUnitAndSubUnitToOrg/OnlyAltinn3.json
test/Altinn.AccessManagement.Tests/Data/Json/AuthorizedParties/MainUnitAndSubUnitToPerson/BothAltinn3AndAltinn2.json
test/Altinn.AccessManagement.Tests/Data/Json/AuthorizedParties/MainUnitAndSubUnitToPerson/OnlyAltinn3.json
test/Altinn.AccessManagement.Tests/Data/Json/AuthorizedParties/PersonGettingA3Delegator/BothAltinn3AndAltinn2.json
test/Altinn.AccessManagement.Tests/Data/Json/AuthorizedParties/PersonGettingA3Delegator/OnlyAltinn3.json
test/Altinn.AccessManagement.Tests/Data/Json/AuthorizedParties/PersonGettingOwnList/BothAltinn3AndAltinn2.json
test/Altinn.AccessManagement.Tests/Data/Json/AuthorizedParties/PersonToOrg/BothAltinn3AndAltinn2.json
test/Altinn.AccessManagement.Tests/Data/Json/AuthorizedParties/PersonToOrg/OnlyAltinn3.json
test/Altinn.AccessManagement.Tests/Data/Json/AuthorizedParties/PersonToPerson/BothAltinn3AndAltinn2.json
test/Altinn.AccessManagement.Tests/Data/Json/AuthorizedParties/PersonToPerson/OnlyAltinn3.json
test/Altinn.AccessManagement.Tests/Data/Json/AuthorizedParties/ResourceOwner_GetEnterpriseUserList/BothAltinn3AndAltinn2.json
test/Altinn.AccessManagement.Tests/Data/Json/AuthorizedParties/ResourceOwner_GetOrgList/BothAltinn3AndAltinn2.json
test/Altinn.AccessManagement.Tests/Data/Json/AuthorizedParties/ResourceOwner_GetPersonList/BothAltinn3AndAltinn2.json
test/Altinn.AccessManagement.Tests/Data/Json/AuthorizedParties/SubUnitToPerson/OnlyAltinn3.json

Added mapping function to map the Altinn App Id from the delegation change table in Postgres: "{org}/{appName}" to match the format used by the ResourceRegistry: "app_{org}_{appName}"
- #661

AuthorizedParties: Changed format of Altinn App Id from database to match ResourceRegistry format

---

src/Altinn.AccessManagement.Core/Services/PolicyInformationPoint.cs

Rewrite of PolicyInformationPoint.FindAllDelegations in order to support lookup of delegations providing only subject party id for a receiving organization.
- Moved fetch of MainUnit as first step, in order to perform what was previously done in two steps for lookup of direct delegations to Subject user be possible in a single database lookup.
- Lookup of direct delegations to organization partyIds both support a Subject users KeyRoleUnits or lookup for a single subject organization party
- #681

Update for PIP API with support for organization party subject lookup

---

src/Altinn.AccessManagement.Core/Altinn.AccessManagement.Core.csproj
src/Altinn.AccessManagement.Core/Constants/AuthzConstants.cs
src/Altinn.AccessManagement.Persistence/Altinn.AccessManagement.Persistence.csproj
src/Altinn.AccessManagement/Program.cs
test/Altinn.AccessManagement.Tests/Data/AuthorizedParties/TestDataAuthorizedParties.cs

Update to scope requirement for AuthorizedParties API for resource owners
Scope requirement changed to:
`altinn:accessmanagement/authorizedparties.resourceowner`
- gives access to lookup authorized parties of any third party where the third party have access to any of the resource owners apps or resources
`altinn:accessmanagement/authorizedparties.admin`
- gives access to lookup authorized parties of any third party across all resource owners apps and resources. Only given to select partners.
- #563

Update to scope requirement for AuthorizedParties API for resource owners

---

src/Altinn.AccessManagement/Controllers/AuthorizedPartiesController.cs
test/Bruno/Altinn.AccessManagement/Manual Test Collection/AuthorizedParties/AuthorizedPartyById/KasperGetMain.bru
test/Bruno/Altinn.AccessManagement/Manual Test Collection/AuthorizedParties/AuthorizedPartyById/KasperGetSubunit.bru

- Changed query to find PartyId in list of authorized parties to include subunits
- Changed query to find PartyId in list of authorized parties to exclude mainunit if only hierarchy element without access
- #689

Fix so GET /authorizedparty/{{partyId}} works for subunits

---

src/Altinn.AccessManagement.Core/Clients/Interfaces/IResourceRegistryClient.cs
src/Altinn.AccessManagement.Core/Configuration/CacheConfig.cs
src/Altinn.AccessManagement.Core/Models/BaseAttribute.cs
src/Altinn.AccessManagement.Core/Models/ListObjectResult.cs
src/Altinn.AccessManagement.Core/Models/PaginatedResult.cs
src/Altinn.AccessManagement.Core/Models/ResourceRegistry/SubjectResources.cs
src/Altinn.AccessManagement.Core/Services/Altinn2RightsService.cs
src/Altinn.AccessManagement.Core/Services/AuthorizedPartiesService.cs
src/Altinn.AccessManagement.Core/Services/ContextRetrievalService.cs
src/Altinn.AccessManagement.Core/Services/Interfaces/IAltinn2RightsService.cs
src/Altinn.AccessManagement.Core/Services/Interfaces/IAuthorizedPartiesService.cs
src/Altinn.AccessManagement.Core/Services/Interfaces/IContextRetrievalService.cs
src/Altinn.AccessManagement.Integration/Clients/ResourceRegistryClient.cs
src/Altinn.AccessManagement/Controllers/AuthorizedPartiesController.cs
src/Altinn.AccessManagement/Controllers/ResourceOwnerAPI/ResourceOwnerAuthorizedPartiesController.cs
src/Altinn.AccessManagement/appsettings.json
test/Altinn.AccessManagement.Tests/Contexts/MockContext.cs
test/Altinn.AccessManagement.Tests/Contexts/ResourceRegistryMock.cs
test/Altinn.AccessManagement.Tests/Controllers/ResourceOwnerAPI/ResourceOwnerAuthorizedPartiesControllerTest.cs
test/Altinn.AccessManagement.Tests/Data/AuthorizedParties/TestDataAuthorizedParties.cs
test/Altinn.AccessManagement.Tests/Data/Json/AuthorizedParties/ResourceOwner_GetEnterpriseUserList/InclResourcesThroughRoles.json
test/Altinn.AccessManagement.Tests/Data/Json/AuthorizedParties/ResourceOwner_GetOrgList/InclResourcesThroughRoles.json
test/Altinn.AccessManagement.Tests/Data/Json/AuthorizedParties/ResourceOwner_GetPersonList/InclResourcesThroughRoles.json
test/Altinn.AccessManagement.Tests/Data/Resources/subjectResources.json
test/Altinn.AccessManagement.Tests/Mocks/ResourceRegistryClientMock.cs

- New query param for AuthorizedParties ResourceOwner API: includeAuthorizedResourcesThroughRoles
- New ResourceRegistryClient.GetSubjectResources implementation
- New ContextRetrievalService.GetSubjectResources  implementation with caching individual role subject resources
- AuthorizedPartiesService implementation updated with enrichment of AuthorizedResources per party based on AuthorizedRoles for the party
- #718

AuthorizedParties | Include authorized resources through roles

---

src/Altinn.AccessManagement.Core/Repositories/Interfaces/IDelegationMetadataRepository.cs
src/Altinn.AccessManagement.Persistence/DelegationMetadataRepo.cs
src/Altinn.AccessManagement.Persistence/Extensions/PersistenceDependencyInjectionExtensions.cs
src/Altinn.AccessManagement.Persistence/ResourceMetadataRepo.cs

- Added autoprepare to db connectionstring setup in persistance setup
- Removed use of Dapper in ResourceMetadataRepo
- Starte removal of Dapper in Insert methods in DelegationMetadataRepo
- #558

Rewrite new Repo implementations away from Dapper

---

test/Bruno/Altinn.AccessManagement/Manual Test Collection/AuthorizedParties/AsAuthenticatedUser/Kasper TT02.bru
test/Bruno/Altinn.AccessManagement/Manual Test Collection/AuthorizedParties/AsAuthenticatedUser/Ostekake TT02.bru
test/Bruno/Altinn.AccessManagement/Manual Test Collection/AuthorizedParties/AsAuthenticatedUser/Ostekake.bru
test/Bruno/Altinn.AccessManagement/Manual Test Collection/AuthorizedParties/AsAuthenticatedUser/Prod.bru
test/Bruno/Altinn.AccessManagement/Manual Test Collection/AuthorizedParties/AsServiceOwner/KasperByNationalIdentity.bru
test/Bruno/Altinn.AccessManagement/Manual Test Collection/AuthorizedParties/AsServiceOwner/KasperByPartyId.bru
test/Bruno/Altinn.AccessManagement/Manual Test Collection/AuthorizedParties/AsServiceOwner/KasperByUserId.bru
test/Bruno/Altinn.AccessManagement/Manual Test Collection/AuthorizedParties/AsServiceOwner/OrstaECUserByUsername.bru
test/Bruno/Altinn.AccessManagement/Manual Test Collection/AuthorizedParties/AsServiceOwner/OrstaECUserByUuid.bru
test/Bruno/Altinn.AccessManagement/Manual Test Collection/AuthorizedParties/AsServiceOwner/ØrstaByOrgNo.bru
test/Bruno/Altinn.AccessManagement/Manual Test Collection/AuthorizedParties/AsServiceOwner/ØrstaByPartyId.bru
test/Bruno/Altinn.AccessManagement/Manual Test Collection/AuthorizedParties/AsServiceOwner/ØrstaByUuid.bru
test/Bruno/Altinn.AccessManagement/Manual Test Collection/PolicyInformationPoint/GetDelegationChanges/Karlstad for MainUnit.bru
test/Bruno/Altinn.AccessManagement/Manual Test Collection/PolicyInformationPoint/GetDelegationChanges/Karlstad for Ørsta.bru
test/Bruno/Altinn.AccessManagement/Manual Test Collection/PolicyInformationPoint/GetDelegationChanges/Paula for MainUnit.bru
test/Bruno/Altinn.AccessManagement/Manual Test Collection/PolicyInformationPoint/GetDelegationChanges/Paula for Ørsta.bru
test/Bruno/Altinn.AccessManagement/Manual Test Collection/RightsInternal/ClearAccessCache/Ørsta to Ostekake.bru
test/Bruno/Altinn.AccessManagement/environments/PROD.bru

- Updated ResourceOwner AuthorizedParties requests for updated Scope requirement
- Added some of my lokal requests used for testing various scenarios not already covered e.g
-- Cache clearing
-- TT02 requests having different user/party identifiers
-- Prod requests using prod token as env secret

Bruno manual requests update

---

src/Altinn.AccessManagement.Core/Services/MaskinportenSchemaService.cs
test/Altinn.AccessManagement.Tests/Data/Resources/resourceList.json
test/Bruno/Altinn.AccessManagement/Automatic Test Collection/AppsInstanceDelegation/DelegationCheck/AppWithDelegableRights_Ok.bru

Because of change in 
RightsHelper.GetRightsQuery now takes the full ServiceResource model as input to build the rights query, based on the resource's 'authorizationReference' property.
Since the ValidateMaskinportenDelegationModel method use the GET resource/{resourceId} endpoint in ResourceRegistry (which apparently don't return the 'authorizationReference' property), API delegations now fail.
Fix: Updated ValidateMaskinportenDelegationModel  method to also use the ResourceList API endpoint, same as the DelegationCheck operation does.
- #{insert issue number here}

Fix MaskinportenSchema Delegations

---

src/Altinn.AccessManagement.Core/Services/MaskinportenSchemaService.cs
test/Altinn.AccessManagement.Tests/Controllers/MaskinportenSchemaControllerTest.cs
test/Altinn.AccessManagement.Tests/Data/Json/MaskinportenSchema/RevokeReceivedMaskinportenScopeDelegation/jks_undelegable/from_p50005545/to_p50004221/Input_Default.json
test/Altinn.AccessManagement.Tests/Data/Resources/resourceList.json

Duplicate check on resource.Delegable which blocks users from revoking existing active delegations after a resource has been deactivated for new delegations. This should however not block revoke of delgations.
https://github.com/Altinn/altinn-authorization-tmp/issues/89

Remove duplicate Delegable check
